const menuArray = [
  // Fusion Drinks
  { id: 1, name: "Tea", price: 20, category: "Fusion Drinks" },
  { id: 2, name: "Ginger Tea", price: 25, category: "Fusion Drinks" },
  { id: 3, name: "Hot Coffee", price: 40, category: "Fusion Drinks" },
  { id: 4, name: "Fusion Cold Coffee", price: 120, category: "Fusion Drinks" },
  { id: 5, name: "Oreo Cold Coffee", price: 130, category: "Fusion Drinks" },
  { id: 6, name: "Chocolate Cold Coffee", price: 150, category: "Fusion Drinks" },
  { id: 7, name: "Soft Drink", price: 40, category: "Fusion Drinks" },
  { id: 8, name: "Fresh Lime Soda", price: 80, category: "Fusion Drinks" },
  { id: 9, name: "Blue Mojito", price: 99, category: "Fusion Drinks" },
  { id: 10, name: "Mint Mojito", price: 99, category: "Fusion Drinks" },
  { id: 11, name: "Kala Khatta Mojito", price: 99, category: "Fusion Drinks" },
  { id: 12, name: "Strawberry Mojito", price: 99, category: "Fusion Drinks" },
  { id: 13, name: "Lassi", price: 140, category: "Fusion Drinks" },
  
  // Fusion Refreshments
  { id: 14, name: "Maggie", price: 39, category: "Fusion Refreshments" },
  { id: 15, name: "Maggie Pepper", price: 59, category: "Fusion Refreshments" },
  { id: 16, name: "Cheese Maggie", price: 79, category: "Fusion Refreshments" },
  { id: 17, name: "Vegetable Maggie", price: 89, category: "Fusion Refreshments" },
  { id: 18, name: "Hakka Noodles", price: 119, category: "Fusion Refreshments" },
  { id: 19, name: "Vegetable Pasta", price: 129, category: "Fusion Refreshments" },
  { id: 20, name: "White Sauce Pasta", price: 159, category: "Fusion Refreshments" },
  { id: 21, name: "Red Sauce Pasta", price: 159, category: "Fusion Refreshments" },
  { id: 22, name: "Veg Grilled Sandwich", price: 49, category: "Fusion Refreshments" },
  { id: 23, name: "Veg Loaded Grilled Sandwich", price: 69, category: "Fusion Refreshments" },
  { id: 24, name: "Paneer Grilled Sandwich", price: 79, category: "Fusion Refreshments" },
  { id: 25, name: "Crispy Paneer Grilled Sandwich", price: 89, category: "Fusion Refreshments" },
  { id: 26, name: "Cheese Grilled Sandwich", price: 89, category: "Fusion Refreshments" },
  { id: 27, name: "Steam Momos", price: 119, category: "Fusion Refreshments" },
  { id: 28, name: "Fried Momos", price: 139, category: "Fusion Refreshments" },
  { id: 29, name: "Crispy Fried Momos", price: 149, category: "Fusion Refreshments" },
  { id: 30, name: "French Fries", price: 69, category: "Fusion Refreshments" },
  { id: 31, name: "Pepper French Fries", price: 79, category: "Fusion Refreshments" },
  { id: 32, name: "Veg Roll", price: 99, category: "Fusion Refreshments" },
  { id: 33, name: "Veg Puff Roll", price: 129, category: "Fusion Refreshments" },
  { id: 34, name: "Manchow Soup", price: 99, category: "Fusion Refreshments" },
  { id: 35, name: "Momos Manchurian Soup", price: 119, category: "Fusion Refreshments" },
  { id: 36, name: "Egg Noodles", price: 129, category: "Fusion Refreshments" },
  { id: 37, name: "Chicken Noodles", price: 149, category: "Fusion Refreshments" },
  { id: 38, name: "Chicken White Sauce Pasta", price: 179, category: "Fusion Refreshments" },
  { id: 39, name: "Chicken Red Sauce Pasta", price: 179, category: "Fusion Refreshments" },
  { id: 40, name: "Chicken Grilled Sandwich", price: 99, category: "Fusion Refreshments" },
  { id: 41, name: "Chicken Cheese Sandwich", price: 119, category: "Fusion Refreshments" },
  { id: 42, name: "Chicken Lollipop", price: 139, category: "Fusion Refreshments" },
  { id: 43, name: "Chicken Fried Momos", price: 149, category: "Fusion Refreshments" },
  { id: 44, name: "Chicken Crispy Fried Momos", price: 169, category: "Fusion Refreshments" },
  { id: 45, name: "Double Egg Roll", price: 119, category: "Fusion Refreshments" },
  { id: 46, name: "Chicken Roll", price: 139, category: "Fusion Refreshments" },
  { id: 47, name: "Chicken Puff", price: 149, category: "Fusion Refreshments" },
  { id: 48, name: "Chicken Manchow Soup", price: 119, category: "Fusion Refreshments" },
  { id: 49, name: "Chicken Momos Soup", price: 139, category: "Fusion Refreshments" },
  
  // North Indian Veg Main Course
  { id: 50, name: "Fusion Mix Veg", price: 210, category: "North Indian Veg Main Course" },
  { id: 51, name: "Paneer Masala", price: 240, category: "North Indian Veg Main Course" },
  { id: 52, name: "Paneer Butter Masala", price: 260, category: "North Indian Veg Main Course" },
  { id: 53, name: "Mutter Paneer", price: 260, category: "North Indian Veg Main Course" },
  { id: 54, name: "Kadhai Paneer", price: 260, category: "North Indian Veg Main Course" },
  { id: 55, name: "Paneer Do Payaza", price: 270, category: "North Indian Veg Main Course" },
  { id: 56, name: "Panner Lababdar", price: 270, category: "North Indian Veg Main Course" },
  { id: 57, name: "Panner Makhni", price: 270, category: "North Indian Veg Main Course" },
  { id: 58, name: "Mushroom Masala", price: 270, category: "North Indian Veg Main Course" },
  { id: 59, name: "Mushroom Gravy", price: 280, category: "North Indian Veg Main Course" },
  { id: 60, name: "Mushroom Do Payaza", price: 280, category: "North Indian Veg Main Course" },
  
  // Fusion North Indian Non-Veg Main Course
  { id: 61, name: "Chicken Bhunna Masala", price: 230, category: "Fusion North Indian Non-Veg Main Course" },
  { id: 62, name: "Butter Chicken", price: 250, category: "Fusion North Indian Non-Veg Main Course" },
  { id: 63, name: "Kadhai Chicken", price: 250, category: "Fusion North Indian Non-Veg Main Course" },
  { id: 64, name: "Chicken Tikka Masala", price: 270, category: "Fusion North Indian Non-Veg Main Course" },
  { id: 65, name: "Special Fusion Chicken", price: 300, category: "Fusion North Indian Non-Veg Main Course" },
  { id: 66, name: "Chicken Hyderabadi", price: 320, category: "Fusion North Indian Non-Veg Main Course" },
  { id: 67, name: "Chicken Angara", price: 320, category: "Fusion North Indian Non-Veg Main Course" },
  { id: 68, name: "Chicken Rassa", price: 320, category: "Fusion North Indian Non-Veg Main Course" },
  
  // Fusion Veg Starters Special
  { id: 69, name: "Fusion Lollipop", price: 140, category: "Fusion Veg Starters Special" },
  { id: 70, name: "Melty Magic Cheese Balls", price: 150, category: "Fusion Veg Starters Special" },
  { id: 71, name: "Fusion Paneer Cheese Balls", price: 160, category: "Fusion Veg Starters Special" },
  { id: 72, name: "Fusion Mashroom Cheese Balls", price: 170, category: "Fusion Veg Starters Special" },
  { id: 73, name: "Fusion Paneer Chilli Dry", price: 170, category: "Fusion Veg Starters Special" },
  { id: 74, name: "Fusion Mashroom Chilli Dry", price: 180, category: "Fusion Veg Starters Special" },
  { id: 75, name: "Fusion Gobi Chilli Dry", price: 180, category: "Fusion Veg Starters Special" },
  { id: 76, name: "Fusion Manchurian Balls Dry", price: 200, category: "Fusion Veg Starters Special" },
  { id: 77, name: "Panner 65", price: 170, category: "Fusion Veg Starters Special" },
  { id: 78, name: "Chilli Potato", price: 140, category: "Fusion Veg Starters Special" },
  { id: 79, name: "Crispy Chilli Potato", price: 160, category: "Fusion Veg Starters Special" },
  { id: 80, name: "Honey Chilli Potato", price: 170, category: "Fusion Veg Starters Special" },
  
  // Non-Veg Starters (Adding to ensure complete data even though not in categoriesArray)
  { id: 81, name: "Fusion Chicken Lollipop", price: 220, category: "Fusion Non-Veg Starters Special" },
  { id: 82, name: "Melty Magic Chicken Cheese Balls", price: 250, category: "Fusion Non-Veg Starters Special" },
  { id: 83, name: "Fusion Chicken Chilli Dry", price: 230, category: "Fusion Non-Veg Starters Special" },
  { id: 84, name: "Fusion Chicken Manchurian Dry", price: 250, category: "Fusion Non-Veg Starters Special" },
  { id: 85, name: "Fusion Chicken Fry Kabab", price: 200, category: "Fusion Non-Veg Starters Special" },
  { id: 86, name: "Fusion Chicken 65", price: 220, category: "Fusion Non-Veg Starters Special" },
  { id: 87, name: "Chicken Crispy Fry Boneless", price: 250, category: "Fusion Non-Veg Starters Special" },
  
  // Fusion Pizza Special
  { id: 88, name: "Golden Corn Pizza", price: 89, category: "Fusion Pizza Special" },
  { id: 89, name: "Onion Pizza", price: 99, category: "Fusion Pizza Special" },
  { id: 90, name: "Tomato Pizza", price: 99, category: "Fusion Pizza Special" },
  { id: 91, name: "Veg Loaded Pizza", price: 150, category: "Fusion Pizza Special" },
  { id: 92, name: "Peppy Paneer Pizza", price: 170, category: "Fusion Pizza Special" },
  { id: 93, name: "Tandoori Paneer Pizza", price: 180, category: "Fusion Pizza Special" },
  { id: 94, name: "Mushroom Peppy Pizza", price: 180, category: "Fusion Pizza Special" },
  { id: 95, name: "Chicken Crispy Pizza", price: 200, category: "Fusion Pizza Special" },
  { id: 96, name: "Tandoori Chicken Pizza", price: 220, category: "Fusion Pizza Special" },
  { id: 97, name: "Chicken Golden Corn", price: 150, category: "Fusion Pizza Special" },
  { id: 98, name: "Chicken Golden Corn Delight", price: 170, category: "Fusion Pizza Special" },
  { id: 99, name: "Pepper Chicken Tandoor Onion", price: 220, category: "Fusion Pizza Special" },
  
  // Fusion South Indian Main Course (South Dosa in images)
  { id: 100, name: "Dosa Plain", price: 70, category: "Fusion South Indian Main Course" },
  { id: 101, name: "Masala Dosa", price: 90, category: "Fusion South Indian Main Course" },
  { id: 102, name: "Podi Dosa", price: 90, category: "Fusion South Indian Main Course" },
  { id: 103, name: "Podi Masala Dosa", price: 110, category: "Fusion South Indian Main Course" },
  { id: 104, name: "Peri-Peri Dosa", price: 120, category: "Fusion South Indian Main Course" },
  { id: 105, name: "Peri-Peri Masala Dosa", price: 140, category: "Fusion South Indian Main Course" },
  { id: 106, name: "Paper Masala Dosa", price: 110, category: "Fusion South Indian Main Course" },
  { id: 107, name: "Paper Paneer Dosa", price: 140, category: "Fusion South Indian Main Course" },
  { id: 108, name: "Cheese Dosa", price: 150, category: "Fusion South Indian Main Course" },
  { id: 109, name: "Uttapam", price: 80, category: "Fusion South Indian Main Course" },
  { id: 110, name: "Onion Uttapam", price: 90, category: "Fusion South Indian Main Course" },
  { id: 111, name: "Chicken Chilli Dosa", price: 130, category: "Fusion South Indian Main Course" },
  { id: 112, name: "Chicken Cheese Dosa", price: 160, category: "Fusion South Indian Main Course" },
  { id: 113, name: "Chicken Noodles Dosa", price: 160, category: "Fusion South Indian Main Course" },
  
  // Fusion Paratha, Daal, and Rice
  { id: 114, name: "Aalu Paratha", price: 70, category: "Fusion Paratha, Daal, and Rice" },
  { id: 115, name: "Gobi Paratha", price: 80, category: "Fusion Paratha, Daal, and Rice" },
  { id: 116, name: "Cheese Paratha", price: 100, category: "Fusion Paratha, Daal, and Rice" },
  { id: 117, name: "Paneer Paratha", price: 100, category: "Fusion Paratha, Daal, and Rice" },
  { id: 118, name: "Tawa Roti", price: 15, category: "Fusion Paratha, Daal, and Rice" },
  { id: 119, name: "Butter Tawa Roti", price: 20, category: "Fusion Paratha, Daal, and Rice" },
  { id: 120, name: "Butter Paratha", price: 25, category: "Fusion Paratha, Daal, and Rice" },
  { id: 121, name: "Laccha Paratha", price: 35, category: "Fusion Paratha, Daal, and Rice" },
  { id: 122, name: "Fried Daal", price: 80, category: "Fusion Paratha, Daal, and Rice" },
  { id: 123, name: "Sambar", price: 100, category: "Fusion Paratha, Daal, and Rice" },
  { id: 124, name: "Steam Rice", price: 100, category: "Fusion Paratha, Daal, and Rice" },
  { id: 125, name: "Jeera Rice", price: 120, category: "Fusion Paratha, Daal, and Rice" },
  { id: 126, name: "Peas Pulao", price: 130, category: "Fusion Paratha, Daal, and Rice" },
  
  // Briyani Zone (Adding to ensure complete data even though not in categoriesArray)
  { id: 127, name: "Fusion Veg Briyani", price: 130, category: "Fusion Briyani Zone" },
  { id: 128, name: "Paneer Briyani", price: 150, category: "Fusion Briyani Zone" },
  { id: 129, name: "Mushroom Briyani", price: 170, category: "Fusion Briyani Zone" },
  { id: 130, name: "Egg Fried Rice", price: 150, category: "Fusion Briyani Zone" },
  { id: 131, name: "Chicken Fried Rice", price: 180, category: "Fusion Briyani Zone" },
  { id: 132, name: "Royal Chicken Briyani", price: 230, category: "Fusion Briyani Zone" },
  
  // Thali Special (Adding to ensure complete data even though not in categoriesArray)
  { id: 133, name: "Veg Pure Thali", price: 140, category: "Fusion Thali Special", description: "Laccha Pratha, Jeera Rice Bowl, Daal Fry, Mix Veg, Sweets, Salad" },
  { id: 134, name: "Chicken Thali", price: 180, category: "Fusion Thali Special", description: "Plain Pratha, Jeera Rice Bowl, Chicken Masala, Sweets, Salad" }
];

const tableArray = [
  { id: 1, name: "Table 1", orders: [] },
  { id: 2, name: "Table 2", orders: [] },
  { id: 3, name: "Table 3", orders: [] },
  { id: 4, name: "Table 4", orders: [] }
];

const categoriesArray = [
  "Fusion Drinks",
  "Fusion Refreshments",
  "North Indian Veg Main Course",
  "Fusion North Indian Non-Veg Main Course",
  "Fusion Veg Starters Special",
  "Fusion Non-Veg Starters Special",
  "Fusion Pizza Special",
  "Fusion South Indian Main Course",
  "Fusion Paratha, Daal, and Rice",
  "Fusion Briyani Zone",
  "Fusion Thali Special",
];

export { menuArray, tableArray, categoriesArray };